name: CI

on: [push, pull_request]

jobs:
  compile:
    strategy:
      # fail-fast: true
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup V
        uses: vlang/setup-v@v1.3
        with:
          check-latest: true
          stable: true

      - name: Install Discord.v system dependencies
        run: sudo apt-get install --quiet -y libssl-dev

      - name: Install Discord.v fork
        run: v install --git https://github.com/kintrix007/discordv.git

      - name: Compile
        run: v .
