name: CI

on: [push, pull_request]

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Setup V
        uses: vlang/setup-v@v1.3
    
      - name: Checkout
        uses: actions/checkout@v3

      - name: Verify v fmt
        run: |
          v fmt -verify .

  compile:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup V
        uses: vlang/setup-v@v1.3

      - name: Install Discord.v fork
        run: v install --git https://github.com/kintrix007/discordv.git

      - name: Compile
        run: v .
